# Generated by Django 2.1.5 on 2019-02-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_commented',
            new_name='date_commented',
        ),
    ]
